[versions]
accompanistPermissions = "0.37.3"
activityCompose = "1.13.0"
activityKtx = "1.13.0"
androidApplication = "9.3.1"
androidxHilt = "1.4.0"
androidxTestExtJunit = "1.3.0"
appcompat = "1.8.0"
benManesVersions = "0.61.0"
cardview = "1.0.0"
collectionKtx = "1.6.0"
composeBom = "2026.08.00"
composeRichtext = "1.0.0-alpha05"
constraintlayout = "2.2.2"
constraintlayoutCompose = "1.1.2"
coreKtx = "1.19.0"
datastorePreferences = "1.2.1"
desugarJdkLibsNio = "2.1.5"
espressoCore = "3.7.0"
firebaseAnalytics = "23.2.0"
googleServices = "4.5.0"
hilt = "2.60.1"
junit = "4.13.2"
kotlin = "2.4.10"
kotlinPluginSerialization = "2.4.10"
kotlinTest = "2.4.10"
kotlinxCoroutinesTest = "1.11.0"
kotlinxDatetime = "0.8.0"
kotlinxSerializationJson = "1.11.0"
ksp = "2.3.11"
lifecycle = "2.11.0"
material = "1.14.0"
mockitoCore = "5.23.0"
navigation = "2.9.8"
onereedSharedVersion = "1.0"
playServicesLocation = "21.4.0"
recyclerview = "1.4.0"
suncalc = "3.11"
timber = "5.0.1"
truth = "1.4.5"
uiTextGoogleFonts = "1.12.0"

[libraries]
accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidxHiltCompiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxHilt" }
androidxHiltNavigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
androidxTestExtJunit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
collectionKtx = { module = "androidx.collection:collection-ktx", version.ref = "collectionKtx" }
composeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
constraintlayoutCompose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
datastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
desugarJdkLibsNio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugarJdkLibsNio" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
firebaseAnalytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3" }
material3AdaptiveNavigationSuite = { module = "androidx.compose.material3:material3-adaptive-navigation-suite" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
navigationUiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
onereedShared = { module = "org.onereed.shared:app", version.ref = "onereedSharedVersion" }
playServicesLocation = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
richtextCommonmark = { module = "com.halilibo.compose-richtext:richtext-commonmark", version.ref = "composeRichtext" }
richtextUiMaterial3 = { module = "com.halilibo.compose-richtext:richtext-ui-material3", version.ref = "composeRichtext" }
suncalc = { module = "org.shredzone.commons:commons-suncalc", version.ref = "suncalc" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
ui = { module = "androidx.compose.ui:ui" }
uiGraphics = { module = "androidx.compose.ui:ui-graphics" }
uiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
uiTextGoogleFonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
uiTooling = { module = "androidx.compose.ui:ui-tooling" }
uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidApplication" }
benManesVersions = { id = "io.github.ben-manes.versions", version.ref = "benManesVersions" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPluginSerialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
# For core UI in production code
composeRuntime = [
    "activityCompose",
    "constraintlayoutCompose",
    "material3",
    "material3AdaptiveNavigationSuite",
    "ui",
    "uiGraphics",
    "uiTextGoogleFonts",
    "uiToolingPreview",
]

# For core Navigation in production code
navigationRuntime = ["navigationCompose", "navigationUiKtx"]

lifecycleRuntime = ["lifecycleRuntimeKtx", "lifecycleViewmodelCompose", "lifecycleViewmodelKtx"]

# For Markdown rendering support
markdownRuntime = ["richtextUiMaterial3", "richtextCommonmark"]

# For core Hilt in production code
# Note: The hiltProcessor bundle must be added separately using the 'ksp' configuration.
hiltRuntime = ["hiltAndroid", "androidxHiltNavigationCompose"]

# For Hilt compiler support (ksp processors)
hiltProcessor = ["hiltCompiler", "androidxHiltCompiler"]

# For Previews and the Layout Inspector
composeDebug = ["uiTooling"]

# For local unit tests
unitTest = ["junit", "kotlinTest", "kotlinxCoroutinesTest", "mockitoCore", "truth"]

# For instrumented Android tests
androidTest = ["androidxTestExtJunit", "espressoCore", "uiTestJunit4"]
